# CALIDAD DE DATOS

## IMPORTAR PAQUETES

In [1]:
import numpy as np
import pandas as pd
from janitor import clean_names
import os

## IMPORTAR LOS DATOS

Cargar los datos.

In [3]:
df = pd.read_csv( r"C:\Users\DataScience\ONLINE_DS_THEBRIDGE_DaniCastillo\ML_LEAD SCORING\01_src\01_data_sample\trabajo.csv", sep=",",index_col=0)
df

,origen,fuente,no_enviar_email,no_llamar,compra,visitas_total,tiempo_en_site_total,paginas_vistas_visita,ult_actividad,ambito,ocupacion,conociste_google,conociste_revista,conociste_periodico,conociste_youtube,conociste_facebook,conociste_referencias,score_actividad,score_perfil,descarga_lm
id,,,,,,,,,,,,,,,,,,,,
660737,API,Chat,No,No,0,0.0,0,0.00,Page Visited on Website,Select,Unemployed,No,No,No,No,No,No,15.0,15.0,No
660728,API,Organic Search,No,No,0,5.0,674,2.50,Email Opened,Select,Unemployed,No,No,No,No,No,No,15.0,15.0,No
660727,Landing Page Submission,Direct Traffic,No,No,1,2.0,1532,2.00,Email Opened,Business Administration,Student,No,No,No,No,No,No,14.0,20.0,Yes
660719,Landing Page Submission,Direct Traffic,No,No,0,1.0,305,1.00,Unreachable,Media and Advertising,Unemployed,No,No,No,No,No,No,13.0,17.0,No
660681,Landing Page Submission,Google,No,No,1,2.0,1428,1.00,Converted to Lead,Select,Unemployed,No,No,No,No,No,No,15.0,18.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
579622,API,Direct Traffic,No,No,1,13.0,1409,2.60,SMS Sent,Select,Unemployed,No,No,No,No,No,No,NaN,NaN,No
579615,Landing Page Submission,Direct Traffic,No,No,1,5.0,210,2.50,SMS Sent,Business Administration,Unemployed,No,No,No,No,No,No,14.0,20.0,No
579564,Landing Page Submission,Direct Traffic,Yes,No,1,8.0,1845,2.67,Email Marked Spam,IT Projects Management,Unemployed,No,No,No,No,No,No,15.0,17.0,No
579546,Landing Page Submission,Direct Traffic,No,No,0,2.0,238,2.00,SMS Sent,Media and Advertising,Unemployed,No,No,No,No,No,No,14.0,19.0,Yes
579533,Landing Page Submission,Direct Traffic,No,No,1,6.0,1279,3.00,SMS Sent,Supply Chain Management,Unemployed,No,No,No,No,No,No,15.0,18.0,Yes

## CORRECCIÓN DE NOMBRES DE VARIABLES

### Corrección automática

In [4]:
df = clean_names(df)
df

,origen,fuente,no_enviar_email,no_llamar,compra,visitas_total,tiempo_en_site_total,paginas_vistas_visita,ult_actividad,ambito,ocupacion,conociste_google,conociste_revista,conociste_periodico,conociste_youtube,conociste_facebook,conociste_referencias,score_actividad,score_perfil,descarga_lm
id,,,,,,,,,,,,,,,,,,,,
660737,API,Chat,No,No,0,0.0,0,0.00,Page Visited on Website,Select,Unemployed,No,No,No,No,No,No,15.0,15.0,No
660728,API,Organic Search,No,No,0,5.0,674,2.50,Email Opened,Select,Unemployed,No,No,No,No,No,No,15.0,15.0,No
660727,Landing Page Submission,Direct Traffic,No,No,1,2.0,1532,2.00,Email Opened,Business Administration,Student,No,No,No,No,No,No,14.0,20.0,Yes
660719,Landing Page Submission,Direct Traffic,No,No,0,1.0,305,1.00,Unreachable,Media and Advertising,Unemployed,No,No,No,No,No,No,13.0,17.0,No
660681,Landing Page Submission,Google,No,No,1,2.0,1428,1.00,Converted to Lead,Select,Unemployed,No,No,No,No,No,No,15.0,18.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
579622,API,Direct Traffic,No,No,1,13.0,1409,2.60,SMS Sent,Select,Unemployed,No,No,No,No,No,No,NaN,NaN,No
579615,Landing Page Submission,Direct Traffic,No,No,1,5.0,210,2.50,SMS Sent,Business Administration,Unemployed,No,No,No,No,No,No,14.0,20.0,No
579564,Landing Page Submission,Direct Traffic,Yes,No,1,8.0,1845,2.67,Email Marked Spam,IT Projects Management,Unemployed,No,No,No,No,No,No,15.0,17.0,No
579546,Landing Page Submission,Direct Traffic,No,No,0,2.0,238,2.00,SMS Sent,Media and Advertising,Unemployed,No,No,No,No,No,No,14.0,19.0,Yes
579533,Landing Page Submission,Direct Traffic,No,No,1,6.0,1279,3.00,SMS Sent,Supply Chain Management,Unemployed,No,No,No,No,No,No,15.0,18.0,Yes

### Corrección manual

In [5]:
df.rename(columns = {'tiempo_en_site_total':'tiempo_en_site',
                     'paginas_vistas_visita':'paginas_vistas',}, 
                    inplace=True)
df

,origen,fuente,no_enviar_email,no_llamar,compra,visitas_total,tiempo_en_site,paginas_vistas,ult_actividad,ambito,ocupacion,conociste_google,conociste_revista,conociste_periodico,conociste_youtube,conociste_facebook,conociste_referencias,score_actividad,score_perfil,descarga_lm
id,,,,,,,,,,,,,,,,,,,,
660737,API,Chat,No,No,0,0.0,0,0.00,Page Visited on Website,Select,Unemployed,No,No,No,No,No,No,15.0,15.0,No
660728,API,Organic Search,No,No,0,5.0,674,2.50,Email Opened,Select,Unemployed,No,No,No,No,No,No,15.0,15.0,No
660727,Landing Page Submission,Direct Traffic,No,No,1,2.0,1532,2.00,Email Opened,Business Administration,Student,No,No,No,No,No,No,14.0,20.0,Yes
660719,Landing Page Submission,Direct Traffic,No,No,0,1.0,305,1.00,Unreachable,Media and Advertising,Unemployed,No,No,No,No,No,No,13.0,17.0,No
660681,Landing Page Submission,Google,No,No,1,2.0,1428,1.00,Converted to Lead,Select,Unemployed,No,No,No,No,No,No,15.0,18.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
579622,API,Direct Traffic,No,No,1,13.0,1409,2.60,SMS Sent,Select,Unemployed,No,No,No,No,No,No,NaN,NaN,No
579615,Landing Page Submission,Direct Traffic,No,No,1,5.0,210,2.50,SMS Sent,Business Administration,Unemployed,No,No,No,No,No,No,14.0,20.0,No
579564,Landing Page Submission,Direct Traffic,Yes,No,1,8.0,1845,2.67,Email Marked Spam,IT Projects Management,Unemployed,No,No,No,No,No,No,15.0,17.0,No
579546,Landing Page Submission,Direct Traffic,No,No,0,2.0,238,2.00,SMS Sent,Media and Advertising,Unemployed,No,No,No,No,No,No,14.0,19.0,Yes
579533,Landing Page Submission,Direct Traffic,No,No,1,6.0,1279,3.00,SMS Sent,Supply Chain Management,Unemployed,No,No,No,No,No,No,15.0,18.0,Yes

## VISIÓN GENERAL

In [6]:
df.head()

,origen,fuente,no_enviar_email,no_llamar,compra,visitas_total,tiempo_en_site,paginas_vistas,ult_actividad,ambito,ocupacion,conociste_google,conociste_revista,conociste_periodico,conociste_youtube,conociste_facebook,conociste_referencias,score_actividad,score_perfil,descarga_lm
id,,,,,,,,,,,,,,,,,,,,
660737,API,Chat,No,No,0,0.0,0,0.0,Page Visited on Website,Select,Unemployed,No,No,No,No,No,No,15.0,15.0,No
660728,API,Organic Search,No,No,0,5.0,674,2.5,Email Opened,Select,Unemployed,No,No,No,No,No,No,15.0,15.0,No
660727,Landing Page Submission,Direct Traffic,No,No,1,2.0,1532,2.0,Email Opened,Business Administration,Student,No,No,No,No,No,No,14.0,20.0,Yes
660719,Landing Page Submission,Direct Traffic,No,No,0,1.0,305,1.0,Unreachable,Media and Advertising,Unemployed,No,No,No,No,No,No,13.0,17.0,No
660681,Landing Page Submission,Google,No,No,1,2.0,1428,1.0,Converted to Lead,Select,Unemployed,No,No,No,No,No,No,15.0,18.0,No

## TIPOS DE DATOS

### Identificación

In [7]:
df.dtypes

origen                    object
fuente                    object
no_enviar_email           object
no_llamar                 object
compra                     int64
visitas_total            float64
tiempo_en_site             int64
paginas_vistas           float64
ult_actividad             object
ambito                    object
ocupacion                 object
conociste_google          object
conociste_revista         object
conociste_periodico       object
conociste_youtube         object
conociste_facebook        object
conociste_referencias     object
score_actividad          float64
score_perfil             float64
descarga_lm               object
dtype: object

### Corrección

In [8]:
df = df.astype({'visitas_total':'Int64'})
df.dtypes

origen                    object
fuente                    object
no_enviar_email           object
no_llamar                 object
compra                     int64
visitas_total              Int64
tiempo_en_site             int64
paginas_vistas           float64
ult_actividad             object
ambito                    object
ocupacion                 object
conociste_google          object
conociste_revista         object
conociste_periodico       object
conociste_youtube         object
conociste_facebook        object
conociste_referencias     object
score_actividad          float64
score_perfil             float64
descarga_lm               object
dtype: object

## VALORES ÚNICOS

### Identificación

In [9]:
df.nunique().sort_values()

conociste_revista           1
conociste_youtube           1
no_llamar                   2
no_enviar_email             2
conociste_periodico         2
conociste_google            2
compra                      2
conociste_facebook          2
descarga_lm                 2
conociste_referencias       2
origen                      4
ocupacion                   6
score_perfil               10
score_actividad            11
fuente                     15
ult_actividad              17
ambito                     19
visitas_total              40
paginas_vistas            100
tiempo_en_site           1637
dtype: int64

### Corrección

In [10]:
df.drop(columns = ["conociste_revista", "conociste_youtube"],inplace = True)

## DUPLICADOS

### Identificación

In [11]:
df.duplicated().sum()

np.int64(1222)

### Corrección

In [12]:
df.drop_duplicates(inplace = True)

## SEPARAR NUMÉRICAS Y CATEGÓRICAS

### Categóricas

In [13]:
cat = df.select_dtypes(exclude = 'number').copy()

In [14]:
cat

,origen,fuente,no_enviar_email,no_llamar,ult_actividad,ambito,ocupacion,conociste_google,conociste_periodico,conociste_facebook,conociste_referencias,descarga_lm
id,,,,,,,,,,,,
660737,API,Chat,No,No,Page Visited on Website,Select,Unemployed,No,No,No,No,No
660728,API,Organic Search,No,No,Email Opened,Select,Unemployed,No,No,No,No,No
660727,Landing Page Submission,Direct Traffic,No,No,Email Opened,Business Administration,Student,No,No,No,No,Yes
660719,Landing Page Submission,Direct Traffic,No,No,Unreachable,Media and Advertising,Unemployed,No,No,No,No,No
660681,Landing Page Submission,Google,No,No,Converted to Lead,Select,Unemployed,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...
579622,API,Direct Traffic,No,No,SMS Sent,Select,Unemployed,No,No,No,No,No
579615,Landing Page Submission,Direct Traffic,No,No,SMS Sent,Business Administration,Unemployed,No,No,No,No,No
579564,Landing Page Submission,Direct Traffic,Yes,No,Email Marked Spam,IT Projects Management,Unemployed,No,No,No,No,No
579546,Landing Page Submission,Direct Traffic,No,No,SMS Sent,Media and Advertising,Unemployed,No,No,No,No,Yes
579533,Landing Page Submission,Direct Traffic,No,No,SMS Sent,Supply Chain Management,Unemployed,No,No,No,No,Yes

### Numéricas

In [15]:
num = df.select_dtypes(include='number').copy()

In [16]:
num

,compra,visitas_total,tiempo_en_site,paginas_vistas,score_actividad,score_perfil
id,,,,,,
660737,0,0,0,0.00,15.0,15.0
660728,0,5,674,2.50,15.0,15.0
660727,1,2,1532,2.00,14.0,20.0
660719,0,1,305,1.00,13.0,17.0
660681,1,2,1428,1.00,15.0,18.0
...,...,...,...,...,...,...
579622,1,13,1409,2.60,NaN,NaN
579615,1,5,210,2.50,14.0,20.0
579564,1,8,1845,2.67,15.0,17.0
579546,0,2,238,2.00,14.0,19.0
579533,1,6,1279,3.00,15.0,18.0

## GESTIÓN DE CATEGÓRICAS

### Nulos

#### Identificación

In [17]:
cat.isna().sum().sort_values(ascending = False)

ocupacion                1558
ambito                    569
ult_actividad              68
fuente                     21
no_llamar                   0
no_enviar_email             0
origen                      0
conociste_google            0
conociste_periodico         0
conociste_facebook          0
conociste_referencias       0
descarga_lm                 0
dtype: int64

NO quito los nulos de ocupacion, pq es una informacion relevante

#### Corrección

##### Imputar por un valor

In [18]:
cat.ocupacion.value_counts()

ocupacion
Unemployed              3829
Working Professional     495
Student                  142
Other                     14
Businessman                8
Housewife                  6
Name: count, dtype: int64

In [19]:
cat.ambito.value_counts()

ambito
Select                               951
Finance Management                   732
Marketing Management                 654
Human Resource Management            631
Operations Management                391
Business Administration              320
IT Projects Management               287
Supply Chain Management              279
Banking, Investment And Insurance    263
Media and Advertising                163
Travel and Tourism                   163
International Business               134
Healthcare Management                129
Hospitality Management                92
E-COMMERCE                            87
Retail Management                     78
Rural and Agribusiness                56
E-Business                            44
Services Excellence                   29
Name: count, dtype: int64

In [20]:
cat.ult_actividad.value_counts()

ult_actividad
Email Opened                    2305
SMS Sent                        1843
Page Visited on Website          510
Converted to Lead                350
Chat Conversation                327
Email Bounced                    216
Email Link Clicked               178
Form Submitted on Website         99
Unreachable                       71
Unsubscribed                      42
Had a Phone Conversation          25
View in browser link Clicked       6
Approached upfront                 6
Email Marked Spam                  2
Email Received                     2
Resubscribed to emails             1
Visited Booth in Tradeshow         1
Name: count, dtype: int64

In [21]:
cat.fuente.value_counts()

fuente
Google               2327
Direct Traffic       2015
Organic Search        907
Chat                  360
Reference             258
Referral Sites        104
Facebook               42
bing                    5
google                  4
Click2call              3
Social Media            2
Pay per Click Ads       1
blog                    1
Live Chat               1
youtubechannel          1
Name: count, dtype: int64

#### Variables a imputar

In [22]:
var_imputar_valor = ['ult_actividad',"fuente"]

#### Valor por el que imputar

In [23]:
valor = 'desconocido'

#### Imputar

In [24]:
cat[var_imputar_valor] = cat[var_imputar_valor].fillna(valor)

##### Imputar por la moda

###### Variables a imputar

In [25]:
var_imputar_moda = ['ocupacion','ambito']

###### Funcion para imputar con la moda

In [26]:
def imputar_moda(variable):
    return(variable.fillna(variable.mode()[0]))

###### Imputar con la moda

In [27]:
cat[var_imputar_moda] = cat[var_imputar_moda].apply(imputar_moda)

In [28]:
cat.isna().sum().sort_values(ascending = False)

origen                   0
fuente                   0
no_enviar_email          0
no_llamar                0
ult_actividad            0
ambito                   0
ocupacion                0
conociste_google         0
conociste_periodico      0
conociste_facebook       0
conociste_referencias    0
descarga_lm              0
dtype: int64

### Aunque no hay nulos, les imputo un valor por defecto por si en el fututro me viene algun dato con nulos

In [30]:
var_imputar_valor = ["origen",
                     "fuente ",
                     "no_enviar_email",
                     "no_llamar",
                     "ult_actividad",
                     "conociste_google",
                     "conociste_periodico",
                     "conociste_facebook",
                     "conociste_referencias",
                     "descarga_lm " ]

### Atípicos

#### Categorías poco frecuentes

##### Función para agrupar categorías raras en 'OTROS'

In [55]:
def agrupar_cat_raras(variable, criterio = 0.02):
    #Calcula las frecuencias
    frecuencias = variable.value_counts(normalize=True)
    #Identifica las que están por debajo del criterio
    temp = [cada for cada in frecuencias.loc[frecuencias < criterio].index.values]
    #Las recodifica en 'OTROS'
    temp2 = np.where(variable.isin(temp),'OTROS',variable)
    #Devuelve el resultado
    return(temp2)

##### Variables a imputar

In [56]:
var_imputar_moda = cat.columns.to_list()

##### Aplicar

In [57]:
for variable in var_imputar_moda:
    cat[variable] = agrupar_cat_raras(cat[variable],criterio = 0.02)

## GESTIÓN DE NUMÉRICAS

### Nulos

#### Identificación

In [58]:
num.isna().sum().sort_values(ascending = False)

compra             0
visitas_total      0
tiempo_en_site     0
paginas_vistas     0
score_actividad    0
score_perfil       0
dtype: int64

#### Corrección

### Eliminar la variable
    Aunque tienen muchos nulos las dejo por si acaso, tienen valor

##### Imputar por la mediana

###### Variables a imputar

In [85]:
#  les imputo a todas las variables un valor  por si en el fututro me viene algun dato con nulos

In [59]:
var_imputar_mediana = num.columns.to_list()

###### Funcion para imputar con la mediana

In [60]:
def imputar_mediana(variable):
    if pd.api.types.is_integer_dtype(variable):
        return(variable.fillna(int(variable.median())))
    else:
        return(variable.fillna(variable.median()))

###### Imputar con la mediana

In [61]:
num[var_imputar_mediana] = num[var_imputar_mediana].apply(imputar_mediana)

In [62]:
num.isna().sum().sort_values(ascending = False)

compra             0
visitas_total      0
tiempo_en_site     0
paginas_vistas     0
score_actividad    0
score_perfil       0
dtype: int64

### Atípicos

#### Por desviación típica

##### Identificación

###### Definir el número de desviaciones típicas

In [63]:
num_desv_tip = 4

###### Función que devuelve los índices de los atípicos

In [64]:
def atipicos_desv_tip(variable, num_desv_tip = 4):
    #sacamos los nulos por ahora
    variable = variable.dropna()
    #calculamos los límites
    media = np.mean(variable)
    sd = np.std(variable)
    umbral = sd * num_desv_tip
    lim_inf = media - umbral
    lim_sup = media + umbral
    #encontramos los índices de los que están fuera de los límites
    indices = [indice for indice,valor in variable.items() if valor < lim_inf or valor > lim_sup]
    return(indices)

### Función que cuenta el número de atípicos

In [65]:
def conteo_atipicos(df,variable, num_desv_tip = 4):
    atipicos = atipicos_desv_tip(df[variable], num_desv_tip)
    return(df.loc[atipicos,variable].value_counts())

### Variables a aplicar

In [67]:
var_atipicos_dt = num.columns.to_list()

### Aplicar

In [68]:
for variable in var_atipicos_dt:
    print('\n' + variable + ':\n')
    print(conteo_atipicos(num,variable,num_desv_tip))

compra:

Series([], Name: count, dtype: int64)

visitas_total:

visitas_total
20    10
23     6
19     6
50     5
21     4
25     4
22     2
24     2
28     2
27     2
43     1
30     1
29     1
41     1
32     1
26     1
42     1
Name: count, dtype: Int64

tiempo_en_site:

Series([], Name: count, dtype: int64)

paginas_vistas:

paginas_vistas
11.00    12
14.00     7
13.00     4
15.00     4
16.00     2
12.00     2
20.00     2
12.33     1
11.50     1
Name: count, dtype: int64

score_actividad:

score_actividad
10.0    47
9.0      4
18.0     4
8.0      3
Name: count, dtype: int64

score_perfil:

Series([], Name: count, dtype: int64)

##### Corrección

Eliminar los registros que tengan al menos un atípico en alguna de las variables indicadas.

    - Visitas_totales maximo de 50 visitas

    - paginas_vistas maximo de 20 visitas

*Cuidado: Si se eliminan registros hay que eliminarlos tanto de cat como de num*

#### Por winsorización manual para una variable

##### Corrección

###### Definir el mínimo y máximo tolerable.

###### Aplicar

In [69]:
num.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6052 entries, 660737 to 579533
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   compra           6052 non-null   int64
 1   visitas_total    6052 non-null   Int64
 2   tiempo_en_site   6052 non-null   int64
 3   paginas_vistas   6052 non-null   float64
 4   score_actividad  6052 non-null   float64
 5   score_perfil     6052 non-null   float64
dtypes: Int64(1), float64(3), int64(2)
memory usage: 465.9 KB

In [70]:
num["visitas_total"] = num["visitas_total"].clip(0, 50)
num["paginas_vistas"] = num["paginas_vistas"].clip(0, 20)

In [71]:
cat

,origen,fuente,no_enviar_email,no_llamar,ult_actividad,ambito,ocupacion,conociste_google,conociste_periodico,conociste_facebook,conociste_referencias,descarga_lm
id,,,,,,,,,,,,
660737,API,Chat,No,No,Page Visited on Website,Select,Unemployed,No,No,No,No,No
660728,API,Organic Search,No,No,Email Opened,Select,Unemployed,No,No,No,No,No
660727,Landing Page Submission,Direct Traffic,No,No,Email Opened,Business Administration,Student,No,No,No,No,Yes
660719,Landing Page Submission,Direct Traffic,No,No,OTROS,Media and Advertising,Unemployed,No,No,No,No,No
660681,Landing Page Submission,Google,No,No,Converted to Lead,Select,Unemployed,No,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...
579622,API,Direct Traffic,No,No,SMS Sent,Select,Unemployed,No,No,No,No,No
579615,Landing Page Submission,Direct Traffic,No,No,SMS Sent,Business Administration,Unemployed,No,No,No,No,No
579564,Landing Page Submission,Direct Traffic,Yes,No,OTROS,IT Projects Management,Unemployed,No,No,No,No,No
579546,Landing Page Submission,Direct Traffic,No,No,SMS Sent,Media and Advertising,Unemployed,No,No,No,No,Yes
579533,Landing Page Submission,Direct Traffic,No,No,SMS Sent,Supply Chain Management,Unemployed,No,No,No,No,Yes

In [72]:
num

,compra,visitas_total,tiempo_en_site,paginas_vistas,score_actividad,score_perfil
id,,,,,,
660737,0,0,0,0.00,15.0,15.0
660728,0,5,674,2.50,15.0,15.0
660727,1,2,1532,2.00,14.0,20.0
660719,0,1,305,1.00,13.0,17.0
660681,1,2,1428,1.00,15.0,18.0
...,...,...,...,...,...,...
579622,1,13,1409,2.60,14.0,16.0
579615,1,5,210,2.50,14.0,20.0
579564,1,8,1845,2.67,15.0,17.0
579546,0,2,238,2.00,14.0,19.0
579533,1,6,1279,3.00,15.0,18.0

## GUARDAR DATASETS TRAS CALIDAD DE DATOS

Guarda los avances en df, cat y num con un sufijo para poder guardar o recuperar avances del proyecto.

En formato pickle para no perder las modificaciones de metadatos.

### Definir los nombres de los archivos

In [73]:

# Definir el directorio donde se guardarán los archivos
directorio = r"C:\Users\DataScience\ONLINE_DS_THEBRIDGE_DaniCastillo\ML_LEAD SCORING\01_src\01_data_sample\TRABAJO"

# Rutas de los archivos 
ruta_df = os.path.join(directorio, f"df_resultado_calidad.pickle")
ruta_cat = os.path.join(directorio, f"cat_resultado_calidad.pickle")
ruta_num = os.path.join(directorio, f"num_resultado_calidad.pickle")

### Guardar los archivos

In [74]:
# Guardar los DataFrames en formato pickle
df.to_pickle(ruta_df)
cat.to_pickle(ruta_cat)
num.to_pickle(ruta_num)

print("Archivos guardados con éxito:")

Archivos guardados con éxito: